[App]
Name = "ai.h2o.wave.twitter-sentiment"
Version = "0.1.1"
Title = "Twitter Sentiment"
Description = "Search keywords on twitter and see the sentiments of the latest tweets."
LongDescription="about.md"
Category = "Data Science"
Keywords =  ["Data Science", "Wave", "Open Source", "Sentiment Analysis"]

[Runtime]
Module = "src.app"
MemoryReservation = "4Gi"
MemoryLimit = "6Gi"

[[Env]]
Name = "ACCESS_TOKEN"
Secret = "twitter-sentiment-secrets"
SecretKey = "access_token"

[[Env]]
Name = "ACCESS_TOKEN_SECRET"
Secret = "twitter-sentiment-secrets"
SecretKey = "access_token_secret"

[[Env]]
Name = "CONSUMER_KEY"
Secret = "twitter-sentiment-secrets"
SecretKey = "consumer_key"

[[Env]]
Name = "CONSUMER_SECRET"
Secret = "twitter-sentiment-secrets"
SecretKey = "consumer_secret"