[App]
Name = "ai.h2o.wave.h2o-guess-the-number"
Version = "1.1.0"
Title = "Guess the Number"
Description = "Prove youâ€™re smarter than AI with this simple game."
LongDescription = "about.md"
Category = "Other"
Keywords = ["wave", "wave apps"]

[Runtime]
Module = "guess_the_number.guess"
EnableOIDC = true
RoutingMode = "BASE_URL"
