[App]
Name = "ai.h2o.wave.credit-risk"
Version = "0.3.0"
Title = "Credit Card Risk"
Description = "Demo for business users to review and update model predictions."
LongDescription = "about.md"
Category = "FinServe"
Keywords = ["FinServe", "Wave", "Open Source"]

[Runtime]
Module = "src.app"
MemoryReservation = "4Gi"
MemoryLimit = "6Gi"
RoutingMode = "BASE_URL"
