[App]
Name = "ai.h2o.wave.churn-risk"
Version = "1.0.0"
Title = "Telco Churn Risk"
Description = "Demo to predict churn risk of telco customers and display top reason codes."
LongDescription = "about.md"
Category = "Telecommunications"
Keywords = ["Telecommunications", "Wave", "Open Source"]

[Runtime]
Module = "src.app"
MemoryReservation = "4Gi"
MemoryLimit = "6Gi"
RoutingMode = "BASE_URL"
