[App]
Name = "ai.h2o.wave.explaining-ratings"
Version = "0.1.0"
Title = "Explaining Ratings"
Description = "Application which allows a business user to extracting ratings, and displaying trends as word cloud"
Category = "Data Science"
Keywords = ["Data Science", "Wave", "Open Source"]

[Runtime]
Module = "src.app"
MemoryReservation = "4Gi"
MemoryLimit = "6Gi"
