[App]
Name = "ai.h2o.wave.explaining-ratings"
Version = "1.1.0"
Title = "Explainable Hotel Ratings"
Description = "Demo to visually explore and compare predictions from text data."
LongDescription = "about.md"
Category = "Data Science"
Keywords = ["NLP", "Wave", "Open Source"]

[Runtime]
Module = "src.app"
MemoryReservation = "4Gi"
MemoryLimit = "6Gi"
RoutingMode = "BASE_URL"
